const data = [
     {
        ref: "10899010",
        name:"Heart of the Ocean",
        character:"Rose",
        price: 1200000.00,
        material: "White Gold",
        description:"Crafted from the finest platinum, this serpentine chain exudes luxury and sophistication with its sleek design and impeccable craftsmanship.",
        category: "Movie",
        type: "Necklace",
        news: false,
        offer: false,
        imgJewelUrl:"./imgs/titannic.jpg",
        imgMovieUrl:"./imgs/Titanic.jpg",
     },

     {
        ref: "10899011",
        name:"María Antonieta",
        character:"María Antonieta",
        price: 1252599.00,
        material: "Gold",
        description:"Elevate your style with this 18k gold Figaro chain, featuring intricately interlocking links that exude timeless elegance and refinement.",
        category: "Movie",
        type: "Necklace",
        news: false,
        offer: false,
        imgJewelUrl: "./imgs/Antonia.jpg",
        imgMovieUrl: "./imgs/Antoniapeli.jpg",
     },

     {
        ref: "10899012",
        name:"Bridgerton",
        character:"Daphne",
        price: 2800900.00,
        material: "Silver Pendant",
        description:"Make a bold statement with this white gold rope chain embellished with vibrant sapphires, a captivating blend of luxury and glamour.",
        category: "Serie",
        type: "Necklace",
        news: false,
        offer: false,
        imgJewelUrl: "./imgs/Brigerton.jpg",
        imgMovieUrl: "./imgs/Brigertonpeli.jpg",
     },

     {
        ref: "10899013",
        name:"The Other Boleyn Girl",
        character:"Ana Bolena",
        price: 4990900.00,
        material: "Pearls and Gold Pendant",
        description:"Immerse yourself in extravagance with this platinum Byzantine chain, characterized by its intricate woven pattern and unmatched beauty.",
        category: "Movie",
        type: "Necklace",
        news: false,
        offer: false,
        imgJewelUrl: "./imgs/B.jpg",
        imgMovieUrl: "./imgs/Girl.jpg",
     },

     {
        ref: "10899014",
        name:"Ocean's 8",
        character:"Daphne Kluger",
        price: 3790900.00,
        material: "Diamond",
        description:"Embrace sophistication with this rose gold Franco chain accentuated by radiant emeralds, epitomizing luxury and prestige.",
        category: "Movie",
        type: "Necklace",
        news: false,
        offer: false,
        imgJewelUrl: "./imgs/Ocean.jpg",
        imgMovieUrl: "./imgs/Oceanpeli.jpg",
     },

     {
        ref: "10899015",
        name:"The Sultan",
        character:"Mahidevran",
        price: 1800900.00,
        material: "Pearls and Gold",
        description:"This exquisite ring features a radiant-cut diamond encircled by a halo of smaller diamonds, set on a platinum band adorned with intricate filigree detailing. Opulent and timeless, this ring embodies sophistication and luxury.",
        category: "Serie",
        type: "Ring",
        news: false,
        offer: false,
        imgJewelUrl: "./imgs/Sultan1.jpg",
        imgMovieUrl: "./imgs/Sultanpeli.jpg",
     },

     {
        ref: "10899016",
        name:"The Sultan",
        character:"Hürrem",
        price: 2500890.00,
        material:"Gold and esmerald" ,
        description: "Exude glamour and sophistication with this diamond tennis chain, featuring a continuous line of exquisite diamonds that shimmer with every movement.",
        category: "Serie",
        type: "Necklace",
        news: true,
        offer: false,
        imgJewelUrl: "./imgs/Sultan2.jpg",
        imgMovieUrl: "./imgs/Sultanpeli.jpg",
     },

     {
        ref: "10899017",
        name:"Bridgerton",
        character:"Daphne",
        price: 55209909.0,
        material: "Pendant",
        description:"Elevate your ensemble with this yellow gold herringbone chain, known for its fluidity and striking presence, a true symbol of luxury and style.",
        category: "Serie",
        type: "Necklace",
        news: false,
        offer: true,
        imgJewelUrl: "./imgs/Brigerton2.jpg",
        imgMovieUrl: "./imgs/Brigertonpeli.jpg",
     },

     {
        ref: "10899018",
        name:"Game of Thrones",
        character:"Arya Stark",
        price: 7470900.00,
        material: "Gold",
        description:"Revel in luxury with this platinum wheat chain adorned with luscious rubies, a striking piece that commands attention and admiration.",
        category: "Serie",
        type: "Necklace",
        news: true,
        offer: false,
        imgJewelUrl: "./imgs/Game\ of\ Thrones.jpg",
        imgMovieUrl: "./imgs/gametronespeli.jpg",
     },

     {
        ref: "10899019",
        name:"Inception",
        character:"Dom Cobb",
        price: 8850900.00,
        material: "White Gold",
        description:"Indulge in understated luxury with this 18k gold box chain, renowned for its simplicity and timeless appeal, perfect for both casual and formal occasions.",
        category: "Movie",
        type: "Necklace",
        news: false,
        offer: false,
        imgJewelUrl: "./imgs/inception.jpg",
        imgMovieUrl: "./imgs/inceptionpeli.jpg",
     },

     {
        ref: "10899020",
        name:"Chernobyl",
        character:"Ulana Khomyuk",
        price: 14800900.00,
        material: "White Gold",
        description:"Indulge in luxury with this stunning cocktail ring crafted from 18k gold. A mesmerizing sapphire center stone is surrounded by a halo of brilliant-cut diamonds, while additional diamonds adorn the band, creating a captivating display of elegance and opulence.",
        category: "Serie",
        type: "Ring",
        news: true,
        offer: false,
        imgJewelUrl: "./imgs/Chernobyl.jpg",
        imgMovieUrl: "./imgs/chernobylpeli.jpg",
     },

     {
        ref: "10899021",
        name:"Friends",
        character:"Rachel Green",
        price: 3450210.00,
        material: "White Gold",
        description:"Adorn yourself with this white gold snake chain accented by sparkling diamonds, an exquisite fusion of style and sophistication.",
        category: "Serie",
        type: "Necklace",
        news: false,
        offer: false,
        imgJewelUrl: "./imgs/Friends.jpg",
        imgMovieUrl: "./imgs/Friendsserie.jpg",
     },

     {
        ref: "10899022",
        name:"Pulp Fiction",
        character:"Jules Winnfield",
        price: 6650620.00,
        material: "White Gold",
        description:"Make a bold statement with this diamond Cuban link chain, featuring a classic design elevated by the brilliance of meticulously set diamonds.",
        category: "Movie",
        type: "Necklace",
        news: false,
        offer: true,
        imgJewelUrl: "./imgs/Forrest\ Gump.jpg",
        imgMovieUrl: "./imgs/pulppeli.jpg",
     },

     {
        ref: "10899023",
        name:"The Matrix",
        character:"Thomas Anderson",
        price: 12890410.00,
        material: "Gold",
        description:"Embrace femininity and luxury with this rose gold rolo chain adorned with delicate pink sapphires, a breathtaking piece that radiates elegance and charm.",
        category: "Movie",
        type: "Necklace",
        news: true,
        offer: false,
        imgJewelUrl: "./imgs/The\ matrix.jpg",
        imgMovieUrl: "./imgs/The\ matrixpeli.jpg",
     },

     {
        ref: "10899024",
        name:"Stranger Things",
        character:"Eleven",
        price: 4840255.00,
        material: "White Gold",
        description: "Crafted from the finest platinum, this tennis chain is adorned with dazzling diamonds, exuding timeless elegance and luxury.",
        category: "Serie",
        type: "Necklace",
        news: false,
        offer: false,
        imgJewelUrl: "./imgs/Stranger.jpg",
        imgMovieUrl: "./imgs/Strangerpeli.jpg",
     },

     {
        ref: "10899025",
        name:"The Queen's Gambit",
        character:"Beth Harmon",
        price: 14830410.00,
        material: "White Gold",
        description:"Elevate your style with this breathtaking ring crafted from lustrous rose gold. A vivid emerald gemstone takes center stage, flanked by shimmering marquise-cut diamonds on either side. ",
        category: "Serie",
        type: "Ring",
        news: false,
        offer: true,
        imgJewelUrl: "./imgs/Gambit1.jpg",
        imgMovieUrl: "./imgs/gambit.jpg",
     },

     
]